### ISSUE TITLE
Working with one shield

### ISSUE THREAD

**Issue by Pepepotero** [rnd-ash/MBUX-Port#3]
Hello,
Sorry if this isn't the correct place to make a question, isn’t an issue.
Today I have received two CAN bus shield. Lamentably one of them are clearly broken. It is possible to test the Arduino code and app with only one shield?
I am not an Arduino expert but I tried to analyzed the code in order to answer me that question. I have a doubt, perhaps a basic doubt about CAN bus shield:
Readme file says 
__"## Connections
I have Set the CS Pins on my CAN C Module to Pin 5, and CAN B Module to Pin 4. Feel free to change these in code:..
// Change these 2 defines if your CS pins are different
// They CANNOT be the same
#define CANB_CS 4
#define CANC_CS 5_"

But seeing the BUS shield board it seems that the pins 4 and 5 are not connected to any component. How the code chooses the correct CAN with each shield? How the code knows that the upper shield is CANB and lower shield is CANC? Do shields need any configuration? or how I can connect one or both to Arduino UNO?
Thank you very much in advance for your help

**Comment by rnd-ash** [comment]
yes, as outlined in the code, my shields use pins 4 and 5 (custom).

I think by default the uni shields use pin 10 for CS. you'll need to do a bit of soldering as the issue is you can't have both shields using the same CS pin. I soldered pin 10 from one shield to pin 4 (removing the leg from pin 10 and did the same for another pin. I recommend you do the same since I know pins 4 and 5 have no adverse effect

**Comment by Pepepotero** [comment]
Thank you very much for your comment.
Yes, the question is answered.
But is it not easiest to modify only one shield (CANB) and remaining the other shield without modification?
And then, the code must be:
#define CANB_CS 4
#define CANC_CS 10
Or this configuration would have any problem. ??

**Comment by rnd-ash** [comment]
that would also work!

**Comment by Pepepotero** [comment]
Thakns. I will test with only one, waitting the second shield.
